import 'package:flutter/material.dart';
import 'package:hexcolor/hexcolor.dart';

Color appColor = HexColor("#3B026A");
Color primaryColor = HexColor("#3B026A");
Color primaryLightColor = HexColor("#868889");
Color whiteLightColor = HexColor("#F9F0FB");
Color pinkColor = HexColor("#FF0067");
Color white = HexColor("#FFFFFF");
Color gray = HexColor("#868889");
Color gray50 = HexColor("#cccecf");
Color lightpink = HexColor("#F6EDF9");
Color lightpink2 = HexColor("#FFD1DF");
Color pink = HexColor("#FE0167");
Color primaryColorLight = HexColor("#FE0167");
Color swiggyOrange = HexColor("#3C0068");
Color secondaryColor = HexColor("#FB6E3B");
Color brownBackGroundColor = HexColor("#F4DBB2");
Color accentColor = HexColor("#FB6E3B");
Color black = HexColor("#000000");
Color grayt = HexColor("#99868889");
Color grayts = HexColor("#99868889");
Color transColor = HexColor("#00FFFFFF");
